Definition of the function `set_null_output` was missing. Added to the file testutil.h ``` /usr/bin/ld: /tmp/test3-54da0c.o: in function `test_goto2': test3.c:(.text+0x2db): undefined reference to `set_null_output' /usr/bin/ld: /tmp/test3-54da0c.o: in function `test_ifeq1': test3.c:(.text+0x52b): undefined reference to `set_null_output' ```